### ISSUE TITLE
Вторая лаба, вариант 22.

### ISSUE THREAD

**Issue by alyona-egorova** [agsh/mipt2016#10]
Удалить элемент примитивного типа из дерева.
Что делать, если дерево состоит из одного элемента примитивного типа? Должно ли удаление проходить по заданному ключу?

**Comment by agsh** [comment]
Удаление можно сделать, например, по значению этого элемента. А вырожденные случаи, когда дерево состоит из одного элемента можно не рассматривать

**Comment by alyona-egorova** [comment]
Спасибо!
