### ISSUE TITLE
Вопрос по проверке второй лабы

### ISSUE THREAD

**Issue by ValeriyaSinevich** [agsh/mipt2016#11]
У меня неделю назад появилась оценка галочка и (5), а теперь исчезла. Что это значит? Что все неправильно? Что Вы поставили проверку по ошибке?

**Comment by ValeriyaSinevich** [comment]
Как выяснилось, я нечаянно отправила второй раз, видимо, в этом причина.
Поставьте, пожалуйста, галочку обратно.

**Comment by agsh** [comment]
Да, засчитывается последний вариант. Проверю и поставлю.
