### ISSUE TITLE
lab3, вариант 7

### ISSUE THREAD

**Issue by voropz** [agsh/mipt2016#13]
> Составить список выпускников ФИВТ, которые любят КВН

Не очень понятно, как парсить Вконтактик. Страница поиска по участникам группы подгружает список скриптом, по мере прокрутки вниз. Соответственно, при обращении к ней с помощью FSharp.Data доступна только небольшая верхняя часть.

**Comment by agsh** [comment]
Можно использовать vk api
[https://api.vk.com/method/groups.getMembers?group_id=fachio&v=5.16&offset=0&count=100&fields=sex,bdate,city,country,photo_200_orig,photo_max_orig&access_token=](https://api.vk.com/method/groups.getMembers?group_id=fachio&v=5.16&offset=0&count=100&fields=sex,bdate,city,country,photo_200_orig,photo_max_orig&access_token=)
Только тогда придётся использовать не HTMLParser, a [JSONParser](http://fsharp.github.io/FSharp.Data/library/JsonValue.html)
