### ISSUE TITLE
22 вариант, lab3

### ISSUE THREAD

**Issue by alyona-egorova** [agsh/mipt2016#14]
Когда делаю HtmlDocument.Load("http://hackage.haskell.org/packages"), то получаю System.OverflowException. Что делать? Как решать?

**Comment by agsh** [comment]
Нужен полный пример кода

**Comment by alyona-egorova** [comment]
Вот та строчка выше - это весь код, который не работает. Если указать любой другой адрес, то все нормально.

**Comment by agsh** [comment]
Ошибка возникает при парсинге закодированных в UTF символов в модуле https://github.com/fsharp/FSharp.Data/blob/master/src/Html/HtmlCharRefs.fs
Избавиться от неё можно, например, заменив такие символы на пробелы

``` fsharp
let get = async {
    let req = HttpWebRequest.Create("http://hackage.haskell.org/packages")
    use! res = req.AsyncGetResponse()
    let stream = res.GetResponseStream()
    let reader = new StreamReader(stream)
    let html = reader.ReadToEnd()
    return html
}
let body = Async.RunSynchronously(get)
HtmlDocument.Parse(body.Replace("&#",""))
```

**Comment by agsh** [comment]
У меня достаточно подождать 10 секунд, чтобы всё прошло:
``` fsharp
open System.Threading
[for i in [1..20] -> try HtmlDocument.Load( "https://github.com/search?l=F%23&o=desc&p=" + i.ToString() + "&q=language%3AF%23&ref=advsearch&s=stars&type=Repositories&utf8=%E2%9C%93"); Thread.Sleep(10000); i with _ -> -1]
```
