### ISSUE TITLE
Лаб 0, Вручтель

### ISSUE THREAD

**Issue by Vruchtel** [agsh/mipt2016#2]
Здравствуйте! Я достаточно давно отправляла решение задачи, но у меня почему-то ощущение, что оно не пришло. Возможно, я что-то сделала не так. Не могли бы Вы проверить, пожалуйста.
Инициалы: "Вручтель С.В." Спасибо.

**Comment by agsh** [comment]
А какой ответ был от сервера (он пишется в конце выполнения программы)? Д.б. быть {ok: true}. А было ли заполнено поле электронной почты?
