### ISSUE TITLE
lab1, ошибка при попытке отправки кода

### ISSUE THREAD

**Issue by egiby** [agsh/mipt2016#3]
![lab1](https://cloud.githubusercontent.com/assets/9490360/14404491/5249071a-fe80-11e5-881e-52ff56424e02.png)
Вот скрин exception'а, вылетающего при запуске main(). Там же видно версию F#, дистрибутив - arch linux. Нулевая лаба отправилась без проблем.

**Comment by agsh** [comment]
Странно, такой маршрут должен работать, Что отвечает простой POST по этому адресу?
Чую неладное в System.Uri, т.к. я тестировал в 3 версии F#

**Comment by egiby** [comment]
А как это сделать без System.Uri?

**Comment by agsh** [comment]
Kubuntu 15.10, F#4, проблема не воспроизводится. Попробуй обновить пакеты mono-develop
