### ISSUE TITLE
Не могу отправить лабу

### ISSUE THREAD

**Issue by alyona-egorova** [agsh/mipt2016#4]
Я 2 часа сегодня отправляла лабу по адресу ladyae@ya.ru, Егорова Алёна. Он мне пишет Ok, true. А вот на сайте не появляется галочки. Но я отправила вам код...

**Comment by agsh** [comment]
Такой почты не зарегистрировано по нулевой лабе :( Я предупреждал

**Comment by alyona-egorova** [comment]
Я отправляла первую лабу, посмотрите там Egorova A.N. Я просто, значит, налажала с почтой со своей. У меня 22 вариант. Я сдала нулевую лабу вовремя.

**Comment by agsh** [comment]
Тогда alena.egorova@phystech.edu
