### ISSUE TITLE
lab1 не заливается

### ISSUE THREAD

**Issue by pavelstrokan** [agsh/mipt2016#5]
хоть и выдаёт заветный 
"{"ok":true}"
на сервере все равно стоит унылый крестик
![trouble](https://cloud.githubusercontent.com/assets/14857859/14405969/311ffa02-fea4-11e5-8d0c-442d1b40bd4c.png)

**Comment by agsh** [comment]
Проверьте, вы посылаете её по той почте, что указывали в первой лабе, т.к. это первичный ключ
