### ISSUE TITLE
Проблемы с доступом к серверу

### ISSUE THREAD

**Issue by Pitovsky** [agsh/mipt2016#6]
При попытке отправить выдает вот такое, кажется, проблемы с вашей стороны:

> main();;
> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
>   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40e375f0 + 0x001af> in <filename unknown>:0 
>   at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x40e354b0 + 0x005a7> in <filename unknown>:0 
>   --- End of inner exception stack trace ---
>   at System.Net.WebClient.UploadValues (System.Uri address, System.String method, System.Collections.Specialized.NameValueCollection data) <0x40dfe850 + 0x00403> in <filename unknown>:0 
>   at System.Net.WebClient.UploadValues (System.Uri address, System.Collections.Specialized.NameValueCollection data) <0x40dfe820 + 0x0001f> in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.Net.WebClient:UploadValues (System.Uri,System.Collections.Specialized.NameValueCollection)
>   at FSI_0002.main () <0x40df7330 + 0x00137> in <filename unknown>:0 
>   at <StartupCode$FSI_0003>.$FSI_0003.main@ () <0x40df72c0 + 0x0000b> in <filename unknown>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7fed481ab910 + 0x000a1> in <filename unknown>:0 
> Stopped due to error
> main();;
> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
>   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40e375f0 + 0x001af> in <filename unknown>:0 
>   at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x40e354b0 + 0x005a7> in <filename unknown>:0 
>   --- End of inner exception stack trace ---
>   at System.Net.WebClient.UploadValues (System.Uri address, System.String method, System.Collections.Specialized.NameValueCollection data) <0x40dfe850 + 0x00403> in <filename unknown>:0 
>   at System.Net.WebClient.UploadValues (System.Uri address, System.Collections.Specialized.NameValueCollection data) <0x40dfe820 + 0x0001f> in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.Net.WebClient:UploadValues (System.Uri,System.Collections.Specialized.NameValueCollection)
>   at FSI_0002.main () <0x40df7330 + 0x00137> in <filename unknown>:0 
>   at <StartupCode$FSI_0004>.$FSI_0004.main@ () <0x40e3a100 + 0x0000b> in <filename unknown>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7fed481ab910 + 0x000a1> in <filename unknown>:0 
> Stopped due to error

**Comment by agsh** [comment]
Не получается подключиться к серверу. Он иногда недоступен. Нужно проверить правильность адреса:91.239.143.158:13666 и попробовать ещё раз

**Comment by Pitovsky** [comment]
Ага, я старый использовал, без порта
