### ISSUE TITLE
Вопрос по заданию

### ISSUE THREAD

**Issue by SecurityQQ** [agsh/mipt2016#7]
@agsh, правильно ли я понимаю, что вариант на вторую лабу тот же, что и на первую? Если да, то объясните задание "Проверить монотонность возрастания ширины уровня дерева". Проверить ширину с ростом глубины? Имеется в виду строгая монотонность? Если можно, то с примером

**Comment by agsh** [comment]
Всё верно, вариант тот же. Имеется в виду нестрогая монотонность, и проверять её нужно по глубине. Например, {a:[1,2,3],b:{c:1}} ширина убывает, а в случае {a:[1,2,3];b:{c:4,d:5,e:6}} сохраняется
